
name: Build and Upload Lambda Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Lambda package in Amazon Linux Docker
        run: |
          # Build dependencies in Amazon Linux Docker (Python 3.11)
          docker run --rm \
            -v "$PWD":/var/task \
            public.ecr.aws/lambda/python:3.12 \
            /bin/bash -c "
              pip install -r requirements.txt -t /var/task/python && \
              cp -r src/* /var/task/python/ && \
              cd /var/task/python && \
              zip -r9 /var/task/function.zip . \
            "

      - name: Upload Lambda package artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda-package
          path: function.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp function.zip s3://${{ secrets.S3_BUCKET_NAME }}/${{ github.ref_name }}/function.zip
